Repository vertelab/odoo-base, pull requests merged in 2020-12, with the labels that each got.

#180 partner_education_view AFC-1515: removed unwanted fields
  partner_education_view/views/res_partner_education_view.xml
Labels: Prio1

#187 [ADD] partner_view_360 AFC-1138: Add field communication_channel in res.partner
  partner_view_360/__manifest__.py
  partner_view_360/models/res_partner.py
  partner_view_360/views/res_partner_view.xml
Labels: Prio1

#181 [ADD] module_chart AFC-1007: adding module module_chart
  module_chart/__init__.py
  module_chart/__manifest__.py
  module_chart/models/__init__.py
  module_chart/models/ir_module.py
  module_chart/static/description/1.png
  module_chart/static/description/icon.png
  module_chart/static/description/index.html
  module_chart/static/description/video.gif
  module_chart/static/src/img/blue_arrow.png
  module_chart/static/src/img/left_click.png
  module_chart/static/src/img/red_arrow.png
  module_chart/static/src/img/right_click.png
  module_chart/static/src/js/graph_module.js
  module_chart/static/src/js/lib/vis.js
  module_chart/static/src/scss/module_graph.scss
  module_chart/static/src/xml/module_graph.xml
  module_chart/views/assets.xml
  module_chart/views/ir_module.xml
Labels: Prio 2, need install / smoke test

#191 partner_view_360: readded code from 12.0-AFC-1548 in order to avoid c…
  partner_view_360/views/res_partner_view.xml
Labels: Prio1, need install / smoke test

#193 partner_tlr_update AFC-1382: fixed the loading of tlr data by hardcod…
  partner_tlr_update/models/res_partner.py
Labels: Prio1

#192 AFC-1119 partner_skills Added Skills Tab on Contact Form
  partner_skills/__manifest__.py
  partner_skills/models/res_partner.py
  partner_skills/security/ir.model.access.csv
  partner_skills/views/res_partner_view.xml
Labels: Prio 2, need install / smoke test

#195 partner_ssn AFC-1562: broke social security number code out of partne…
  partner_ssn/__init__.py
  partner_ssn/__manifest__.py
  partner_ssn/models/__init__.py
  partner_ssn/models/res_partner.py
  partner_view_360/models/res_partner.py
Labels: Prio1

#197 partner_ssn, partner_view_360: moved customer_id_unique sql constrain…
  partner_ssn/models/res_partner.py
  partner_view_360/models/res_partner.py
Labels: Prio1

#198 AFC-1186 base_user_groups_dafa: Added ties to core groups.
  base_user_groups_dafa/__manifest__.py
  base_user_groups_dafa/security/security.xml
Labels: Prio1
