Repository vertelab/odoo-base, pull requests merged in 2021-01, with the labels that each got.

#200 AFC-1544 base_user_groups_dafa: Implemented filtering field for DAFA …
  base_user_groups_dafa/__init__.py
  base_user_groups_dafa/models/__init__.py
  base_user_groups_dafa/models/res_groups.py
  base_user_groups_dafa/security/security.xml
Labels: Prio1

#199 Dev 12.0 dafa afc-1590 added support rules
  base_user_groups_dafa/__manifest__.py
  base_user_groups_dafa/security/security.xml
Labels: Prio1

#201 partner_ssn AFC-1601: removed the use of company_registry
  partner_ssn/models/res_partner.py
Labels: Prio1

#210 Afc 1185 user groups v1 and v2
  base_user_groups_dafa/__manifest__.py
  base_user_groups_dafa/security/security.xml
Labels: Prio1, do not merge yet

#207 12.0 afc 1624 & 1566 moved res.partner.education from res_sun to an own module
  partner_education_views/__manifest__.py
  partner_education_views/data/res.partner.education.education_level.csv
  partner_education_views/models/__init__.py
  partner_education_views/models/education.py
  partner_education_views/models/education_level.py
  partner_education_views/models/res_partner.py
  partner_education_views/security/ir.model.access.csv
  partner_education_views/views/education_level_view.xml
  partner_education_views/views/res_partner_view.xml
  res_sun/__manifest__.py
  res_sun/data/res.partner.education_level.csv
  res_sun/i18n/sv_SE.po
  res_sun/models/__init__.py
  res_sun/models/res_partner.py
  res_sun/security/ir.model.access.csv
  res_sun/views/res_partner_view.xml
Labels: Prio1

#212 Afc 1185 translate base user groups dafa
  base_user_groups_dafa/i18n/sv.po
  base_user_groups_dafa/i18n/sv_SE.po
Labels: Prio1

#219 partner_flip_firstname AFC-1666: new module flips the position of fir…
  partner_flip_firstname/__init__.py
  partner_flip_firstname/__manifest__.py
  partner_flip_firstname/views/res_partner_view.xml
Labels: Prio 2

#221 12.0 afc 1566
  partner_education/__init__.py
  partner_education/__manifest__.py
  partner_education/data/res.partner.education.education_level.csv
  partner_education/models/__init__.py
  partner_education/models/education.py
  partner_education/models/education_level.py
  partner_education/models/res_partner.py
  partner_education/security/ir.model.access.csv
  partner_education/static/description/icon.png
  partner_education/views/education_level_view.xml
  partner_education/views/res_partner_view.xml
  partner_education_360/__init__.py
  partner_education_360/__manifest__.py
  partner_education_360/views/res_partner_view.xml
  partner_view_360/views/res_partner_view.xml
  res_drivers_license/__manifest__.py
  res_drivers_license/models/__init__.py
  res_drivers_license/models/res_drivers_license.py
  res_drivers_license/views/res_partner_view.xml
  res_sun/__manifest__.py
  res_sun/data/res.sun.csv
  res_sun/i18n/sv_SE.po
  res_sun/models/__init__.py
  res_sun/models/res_partner.py
  res_sun/models/res_sun.py
  res_sun/security/ir.model.access.csv
  res_sun/views/res_partner_view.xml
Labels: Prio1

#229 AFC-1586 - res_interpreter_language: interpreter languages
  res_interpreter_language/__init__.py
  res_interpreter_language/__manifest__.py
  res_interpreter_language/models/__init__.py
  res_interpreter_language/models/res_interpreter_language.py
  res_interpreter_language/security/ir.model.access.csv
  res_interpreter_language/views/res_interpreter_language_view.xml
Labels: need install / smoke test
